---
name: Java CI

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DEFAULT_OS: ubuntu-18.04
  DEFAULT_JDK: 7

jobs:
  build:
    name: Build Default Java/OS
    runs-on: '$DEFAULT_OS'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '$DEFAULT_JDK'
      - name: Gradle Clean Build
        run: ./gradlew clean build

  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['$DEFAULT_OS', ubuntu-20.04]
        java: ['$DEFAULT_JDK', 8, 11, 17, 18-ea, 19-ea]
        exclude:
          - os: '$DEFAULT_OS'
            java: '$DEFAULT_JDK'
      fail-fast: false
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Gradle Clean Build
        run: ./gradlew clean build
  qa:
    name: QA Steps
    needs: test
    runs-on: '$DEFAULT_OS'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '$DEFAULT_JDK'
      - name: Gradle JavaDoc
        run: ./gradlew javadoc

...